In [1]:
import numpy as np
import torch
from PIL import Image

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [2]:
points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

In [7]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
print(points_storage[0])
points.storage()[1]

1.0


4.0

In [10]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
print(second_point.storage_offset())
print(second_point.size())
print(torch.Size([2]))

2
torch.Size([2])
torch.Size([2])


In [11]:
# transpose the tensor
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print(points)
points_t = points.t()
print(points_t)
print(id(points.storage()) == id(points_t.storage()))
print(points.stride())
print(points_t.stride())

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])
tensor([[1., 2., 3.],
        [4., 1., 5.]])
True
(2, 1)
(1, 2)


In [14]:
# Numeric Types
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]],dtype=torch.short)
print(double_points)
print(short_points)
double_points = torch.ones(10, 2).double()
short_points = torch.ones(10, 2).short()
print(double_points)
print(short_points)
double_points = torch.ones(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(torch.short)
print(double_points)
print(short_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], d

In [15]:
# to numpy
points = torch.ones(3, 4)
points_np = points.numpy()
print(points)
print(points_np)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# Serializing tensors
torch.save(points, '../data/p1ch3/ourpoints.t')
with open('../data/p1ch3/ourrpoints.t', 'wb') as f:
    torch.save(points, f)
# load
points = torch.load('../data/p1ch3/ourpoints.t')

In [24]:
import h5py
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
dset = f['coords']
last_points = dset[1:]
print(last_points)
last_points = torch.from_numpy(dset[1:])
print(last_points)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [26]:
# moving tensors to the GPU
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device='cuda')
points_gpu = 2*points.to(device='cuda')

In [30]:
# Exercises
a = torch.tensor(list(range(9)))
print(a.size())
print(a.stride())
b = a.view(3,3 )
print(b.size())
print(b.stride())
c = b[1:, 1:]
print(c.size())
print(c.stride())
torch.cos

torch.Size([9])
(1,)
torch.Size([3, 3])
(3, 1)
torch.Size([2, 2])
(3, 1)
